name    'torian-pam'
version '0.0.7'
source 'https://github.com/torian/puppet-pam'
author 'Emiliano Castagnari ecastag@gmail.com (aka Torian)'
license 'Apache'
summary 'PAM module for Puppet.'
description 'Manage PAM configuration via Puppet'
project_page 'https://github.com/torian/puppet-pam'
